frontend:
  port: 9442
homeassistant: 
  legacy_entity_attributes: true
permit_join: false
mqtt:
  base_topic: zbgw03
  server: 'mqtt:/localhost:1883'
  user: ntguest
  password: '170974'
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  adapter: ezsp
advanced:
  pan_id: GENERATE
  network_key: GENERATE
  channel: 15
